# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170719_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='userid',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
