# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170720_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=1000)),
                ('key', models.CharField(max_length=5000)),
            ],
        ),
    ]
