# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('userid', models.CharField(blank=True, max_length=1000)),
                ('requestor', models.GenericIPAddressField()),
            ],
        ),
        migrations.RemoveField(
            model_name='deviceevent',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceEvent',
        ),
    ]
