# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170905_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('period', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
